
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { toast } from "@/hooks/use-toast";
import { 
  Download, 
  FileText, 
  FileSpreadsheet, 
  TableIcon,
  FileCode,
  AlertTriangle,
  MapPin,
  Wind
} from "lucide-react";

interface EnhancedReportGenerationProps {
  modelParams: any;
  results: any;
  multipleSourceResults?: any;
  timestamp?: string;
}

const EnhancedReportGeneration = ({ 
  modelParams, 
  results, 
  multipleSourceResults,
  timestamp = new Date().toISOString() 
}: EnhancedReportGenerationProps) => {
  
  const generateMarkdownReport = () => {
    const reportId = `ELDSM-${timestamp.substring(0, 10).replace(/-/g, '')}-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`;
    
    const markdown = `# Emergency Leakage and Dispersion Model Report

**Report ID:** ${reportId}  
**Generated:** ${new Date(timestamp).toLocaleString()}  
**Chemical:** ${modelParams.chemicalType}  
**Release Rate:** ${modelParams.releaseRate.toFixed(4)} kg/min  

## Weather Conditions
- **Wind Speed:** ${modelParams.windSpeed.toFixed(4)} m/s
- **Wind Direction:** ${modelParams.windDirection}° (${getWindDirectionLabel(modelParams.windDirection)})
- **Stability Class:** ${modelParams.stabilityClass}
- **Temperature:** ${modelParams.temperature.toFixed(4)}°C

## Source Location
- **Coordinates:** ${modelParams.sourceLocation.lat.toFixed(4)}, ${modelParams.sourceLocation.lng.toFixed(4)}
- **Source Height:** ${modelParams.sourceHeight || 2.0000} m

## Hazard Zones

### Red Zone (Immediate Danger)
- **Distance:** ${results.redZone.distance.toFixed(4)} km
- **Concentration:** ${results.redZone.concentration.toFixed(4)} mg/m³
- **Area:** ${results.redZone.area.toFixed(4)} km²
- **Population at Risk:** ${results.redZone.populationAtRisk}

### Orange Zone (Hazardous)
- **Distance:** ${results.orangeZone.distance.toFixed(4)} km
- **Concentration:** ${results.orangeZone.concentration.toFixed(4)} mg/m³
- **Area:** ${results.orangeZone.area.toFixed(4)} km²
- **Population at Risk:** ${results.orangeZone.populationAtRisk}

### Yellow Zone (Caution)
- **Distance:** ${results.yellowZone.distance.toFixed(4)} km
- **Concentration:** ${results.yellowZone.concentration.toFixed(4)} mg/m³
- **Area:** ${results.yellowZone.area.toFixed(4)} km²
- **Population at Risk:** ${results.yellowZone.populationAtRisk}

## Dispersion Analysis
- **Mass Released:** ${results.massReleased.toFixed(4)} kg
- **Evaporation Rate:** ${results.evaporationRate.toFixed(4)} kg/s
- **Maximum Concentration:** ${results.maximumConcentration.toFixed(4)} mg/m³
- **Lethal Distance:** ${results.lethalDistance.toFixed(4)} km

## Detection & Response
- **Detection Probability:** ${(results.detectionProbability * 100).toFixed(2)}%
- **Time to Detection:** ${results.timeToDetection.toFixed(4)} minutes
- **Evacuation Time:** ${results.evacuationTime.toFixed(4)} minutes

${multipleSourceResults ? `
## Multiple Source Analysis
- **Total Sources:** ${multipleSourceResults.individualSources.length + 1}
- **Combined Max Distance:** ${multipleSourceResults.combinedZones.yellow.distance.toFixed(4)} km
- **Total Mass Released:** ${multipleSourceResults.totalMassReleased.toFixed(4)} kg
- **Total Affected Population:** ${multipleSourceResults.affectedPopulation}
` : ''}

## Recommendations
1. Establish evacuation perimeter at ${results.orangeZone.distance.toFixed(4)} km minimum
2. Deploy emergency response teams with appropriate PPE
3. Monitor wind conditions for potential plume direction changes
4. Activate emergency alert systems for affected populations

---
*This report was generated by the Emergency Leakage and Dispersion Selection Model (ELDSM)*
`;

    // Create and download the markdown file
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ELDSM_Report_${reportId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Markdown Report Generated",
      description: "Emergency response report has been downloaded as Markdown file.",
    });
  };
  
  const generateExcelData = () => {
    // Create CSV data that can be opened in Excel
    const csvData = [
      ['Emergency Leakage and Dispersion Model Report'],
      [''],
      ['Report ID', `ELDSM-${timestamp.substring(0, 10).replace(/-/g, '')}-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`],
      ['Generated', new Date(timestamp).toLocaleString()],
      ['Chemical', modelParams.chemicalType],
      ['Release Rate (kg/min)', modelParams.releaseRate.toFixed(4)],
      [''],
      ['Weather Conditions'],
      ['Wind Speed (m/s)', modelParams.windSpeed.toFixed(4)],
      ['Wind Direction (°)', modelParams.windDirection.toFixed(4)],
      ['Stability Class', modelParams.stabilityClass],
      ['Temperature (°C)', modelParams.temperature.toFixed(4)],
      [''],
      ['Source Location'],
      ['Latitude', modelParams.sourceLocation.lat.toFixed(4)],
      ['Longitude', modelParams.sourceLocation.lng.toFixed(4)],
      [''],
      ['Zone', 'Distance (km)', 'Concentration (mg/m³)', 'Area (km²)', 'Population at Risk'],
      ['Red Zone', results.redZone.distance.toFixed(4), results.redZone.concentration.toFixed(4), results.redZone.area.toFixed(4), results.redZone.populationAtRisk],
      ['Orange Zone', results.orangeZone.distance.toFixed(4), results.orangeZone.concentration.toFixed(4), results.orangeZone.area.toFixed(4), results.orangeZone.populationAtRisk],
      ['Yellow Zone', results.yellowZone.distance.toFixed(4), results.yellowZone.concentration.toFixed(4), results.yellowZone.area.toFixed(4), results.yellowZone.populationAtRisk],
      [''],
      ['Dispersion Analysis'],
      ['Mass Released (kg)', results.massReleased.toFixed(4)],
      ['Evaporation Rate (kg/s)', results.evaporationRate.toFixed(4)],
      ['Maximum Concentration (mg/m³)', results.maximumConcentration.toFixed(4)],
      ['Lethal Distance (km)', results.lethalDistance.toFixed(4)],
      [''],
      ['Detection & Response'],
      ['Detection Probability (%)', (results.detectionProbability * 100).toFixed(2)],
      ['Time to Detection (min)', results.timeToDetection.toFixed(4)],
      ['Evacuation Time (min)', results.evacuationTime.toFixed(4)]
    ];

    // Add concentration profile data
    csvData.push([''], ['Concentration Profile']);
    csvData.push(['Distance (km)', 'Concentration (mg/m³)']);
    results.concentrationProfile.forEach((point: any) => {
      csvData.push([point.distance.toFixed(4), point.concentration.toFixed(4)]);
    });

    const csvContent = csvData.map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ELDSM_Data_${timestamp.substring(0, 10).replace(/-/g, '')}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Excel Data Generated",
      description: "Simulation data has been exported to CSV format for Excel.",
    });
  };
  
  const generateJSONReport = () => {
    const reportData = {
      reportId: `ELDSM-${timestamp.substring(0, 10).replace(/-/g, '')}-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`,
      timestamp,
      modelParameters: {
        ...modelParams,
        releaseRate: parseFloat(modelParams.releaseRate.toFixed(4)),
        windSpeed: parseFloat(modelParams.windSpeed.toFixed(4)),
        windDirection: parseFloat(modelParams.windDirection.toFixed(4)),
        temperature: parseFloat(modelParams.temperature.toFixed(4)),
        sourceLocation: {
          lat: parseFloat(modelParams.sourceLocation.lat.toFixed(4)),
          lng: parseFloat(modelParams.sourceLocation.lng.toFixed(4))
        }
      },
      results: {
        ...results,
        redZone: {
          ...results.redZone,
          distance: parseFloat(results.redZone.distance.toFixed(4)),
          concentration: parseFloat(results.redZone.concentration.toFixed(4)),
          area: parseFloat(results.redZone.area.toFixed(4))
        },
        orangeZone: {
          ...results.orangeZone,
          distance: parseFloat(results.orangeZone.distance.toFixed(4)),
          concentration: parseFloat(results.orangeZone.concentration.toFixed(4)),
          area: parseFloat(results.orangeZone.area.toFixed(4))
        },
        yellowZone: {
          ...results.yellowZone,
          distance: parseFloat(results.yellowZone.distance.toFixed(4)),
          concentration: parseFloat(results.yellowZone.concentration.toFixed(4)),
          area: parseFloat(results.yellowZone.area.toFixed(4))
        },
        massReleased: parseFloat(results.massReleased.toFixed(4)),
        evaporationRate: parseFloat(results.evaporationRate.toFixed(4)),
        maximumConcentration: parseFloat(results.maximumConcentration.toFixed(4)),
        lethalDistance: parseFloat(results.lethalDistance.toFixed(4))
      },
      multipleSourceResults
    };

    const jsonContent = JSON.stringify(reportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ELDSM_Report_${reportData.reportId}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "JSON Report Generated",
      description: "Complete data has been exported to JSON format.",
    });
  };

  const getWindDirectionLabel = (direction: number): string => {
    const directions = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];
    const index = Math.round(((direction % 360) / 45)) % 8;
    return directions[index];
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Enhanced Report Generation
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
          <Card className="p-3 border border-dashed">
            <div className="flex flex-col h-full">
              <div className="flex items-center gap-2 mb-2">
                <FileCode className="h-5 w-5 text-blue-500" />
                <span className="font-medium text-sm">Markdown Report</span>
              </div>
              <div className="text-xs text-muted-foreground mb-3 flex-1">
                Human-readable report in Markdown format with complete analysis.
              </div>
              <Button 
                onClick={generateMarkdownReport}
                variant="outline"
                size="sm"
                className="w-full"
              >
                <Download className="h-3 w-3 mr-1" />
                Generate MD
              </Button>
            </div>
          </Card>
          
          <Card className="p-3 border border-dashed">
            <div className="flex flex-col h-full">
              <div className="flex items-center gap-2 mb-2">
                <FileSpreadsheet className="h-5 w-5 text-green-500" />
                <span className="font-medium text-sm">Excel Data</span>
              </div>
              <div className="text-xs text-muted-foreground mb-3 flex-1">
                Structured data tables for analysis in Excel format.
              </div>
              <Button 
                onClick={generateExcelData}
                variant="outline"
                size="sm"
                className="w-full"
              >
                <Download className="h-3 w-3 mr-1" />
                Export Excel
              </Button>
            </div>
          </Card>
          
          <Card className="p-3 border border-dashed">
            <div className="flex flex-col h-full">
              <div className="flex items-center gap-2 mb-2">
                <FileCode className="h-5 w-5 text-purple-500" />
                <span className="font-medium text-sm">JSON Report</span>
              </div>
              <div className="text-xs text-muted-foreground mb-3 flex-1">
                Machine-readable format for API integration and automation.
              </div>
              <Button 
                onClick={generateJSONReport}
                variant="outline"
                size="sm"
                className="w-full"
              >
                <Download className="h-3 w-3 mr-1" />
                Export JSON
              </Button>
            </div>
          </Card>

          <Card className="p-3 border border-dashed">
            <div className="flex flex-col h-full">
              <div className="flex items-center gap-2 mb-2">
                <AlertTriangle className="h-5 w-5 text-orange-500" />
                <span className="font-medium text-sm">Emergency Brief</span>
              </div>
              <div className="text-xs text-muted-foreground mb-3 flex-1">
                Quick summary for emergency responders and decision makers.
              </div>
              <Button 
                variant="outline"
                size="sm"
                className="w-full"
                onClick={() => toast({ title: "Coming Soon", description: "Emergency brief format will be available in the next update." })}
              >
                <Download className="h-3 w-3 mr-1" />
                Brief
              </Button>
            </div>
          </Card>
        </div>
        
        <Separator />
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div className="space-y-2">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Report ID:</span>
              <span className="font-mono text-xs">
                ELDSM-{timestamp.substring(0, 10).replace(/-/g, '')}-{Math.floor(Math.random() * 10000).toString().padStart(4, '0')}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Chemical:</span>
              <Badge variant="outline">{modelParams.chemicalType}</Badge>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Release Rate:</span>
              <span>{modelParams.releaseRate.toFixed(4)} kg/min</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Max Distance:</span>
              <span>{results.yellowZone.distance.toFixed(4)} km</span>
            </div>
          </div>
          
          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <span className="text-muted-foreground">Wind:</span>
              <div className="flex items-center gap-1">
                <Wind className="h-3 w-3" />
                <span>{modelParams.windSpeed.toFixed(1)} m/s {getWindDirectionLabel(modelParams.windDirection)}</span>
              </div>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Location:</span>
              <div className="flex items-center gap-1">
                <MapPin className="h-3 w-3" />
                <span className="text-xs">{modelParams.sourceLocation.lat.toFixed(4)}, {modelParams.sourceLocation.lng.toFixed(4)}</span>
              </div>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Population Risk:</span>
              <span>{(results.redZone.populationAtRisk + results.orangeZone.populationAtRisk).toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Generated:</span>
              <span className="text-xs">{new Date(timestamp).toLocaleString()}</span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default EnhancedReportGeneration;
